from pathlib import Path
from nltk import word_tokenize, pos_tag
from nltk.corpus import wordnet
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re


# 移除所有数字和标点符号
def remove_num_and_punct(text):
    remove_chars = '[0-9’!"#$%&\'()*+,-./:;<=>?@，。?★、…【】《》？“”‘’！[\\]^_`{|}~]+'
    return re.sub(remove_chars, '', text)


# 递归获取该路径下的所有文件
def get_all_txt_file(root_path: Path):
    txt_file_list = []
    for file in root_path.iterdir():
        if file.is_dir():
            txt_file_list.extend(get_all_txt_file(file))
        else:
            if file.name[-4:] == '.txt':
                txt_file_list.append('/'.join(file.parts))
    return txt_file_list


# 获取单词的词性
def get_wordnet_pos(tag):
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        return None


if __name__ == "__main__":
    # 停用词列表
    stop_words_list = [
        "\'",
        "\"",
        "a",
        "able",
        "about",
        "above",
        "according",
        "accordingly",
        "across",
        "actually",
        "after",
        "afterwards",
        "again",
        "against",
        "all",
        "allow",
        "allows",
        "almost",
        "alone",
        "along",
        "already",
        "also",
        "although",
        "always",
        "am",
        "among",
        "amongst",
        "an",
        "and",
        "another",
        "any",
        "anybody",
        "anyhow",
        "anyone",
        "anything",
        "anyway",
        "anyways",
        "anywhere",
        "apart",
        "appear",
        "appreciate",
        "appropriate",
        "are",
        "around",
        "as",
        "aside",
        "ask",
        "asking",
        "associated",
        "at",
        "available",
        "away",
        "awfully",
        "b",
        "be",
        "became",
        "because",
        "become",
        "becomes",
        "becoming",
        "been",
        "before",
        "beforehand",
        "behind",
        "being",
        "believe",
        "below",
        "beside",
        "besides",
        "best",
        "better",
        "between",
        "beyond",
        "both",
        "brief",
        "but",
        "by",
        "c",
        "came",
        "can",
        "cannot",
        "cant",
        "cause",
        "causes",
        "certain",
        "certainly",
        "changes",
        "clearly",
        "co",
        "com",
        "come",
        "comes",
        "concerning",
        "consequently",
        "consider",
        "considering",
        "contain",
        "containing",
        "contains",
        "corresponding",
        "could",
        "course",
        "currently",
        "d",
        "definitely",
        "described",
        "despite",
        "did",
        "different",
        "do",
        "does",
        "doing",
        "done",
        "down",
        "downwards",
        "during",
        "e",
        "each",
        "edu",
        "eg",
        "eight",
        "either",
        "else",
        "elsewhere",
        "enough",
        "entirely",
        "especially",
        "et",
        "etc",
        "even",
        "ever",
        "every",
        "everybody",
        "everyone",
        "everything",
        "everywhere",
        "ex",
        "exactly",
        "example",
        "except",
        "f",
        "far",
        "few",
        "fifth",
        "first",
        "five",
        "followed",
        "following",
        "follows",
        "for",
        "former",
        "formerly",
        "forth",
        "four",
        "from",
        "further",
        "furthermore",
        "g",
        "get",
        "gets",
        "getting",
        "given",
        "gives",
        "go",
        "goes",
        "going",
        "gone",
        "got",
        "gotten",
        "greetings",
        "h",
        "had",
        "happens",
        "hardly",
        "has",
        "have",
        "having",
        "he",
        "hello",
        "help",
        "hence",
        "her",
        "here",
        "hereafter",
        "hereby",
        "herein",
        "hereupon",
        "hers",
        "herself",
        "hi",
        "him",
        "himself",
        "his",
        "hither",
        "hopefully",
        "how",
        "howbeit",
        "however",
        "i",
        "ie",
        "if",
        "ignored",
        "immediate",
        "in",
        "inasmuch",
        "inc",
        "indeed",
        "indicate",
        "indicated",
        "indicates",
        "inner",
        "insofar",
        "instead",
        "into",
        "inward",
        "is",
        "it",
        "its",
        "itself",
        "j",
        "just",
        "k",
        "keep",
        "keeps",
        "kept",
        "know",
        "knows",
        "known",
        "l",
        "last",
        "lately",
        "later",
        "latter",
        "latterly",
        "least",
        "less",
        "lest",
        "let",
        "like",
        "liked",
        "likely",
        "little",
        "look",
        "looking",
        "looks",
        "ltd",
        "m",
        "mainly",
        "many",
        "may",
        "maybe",
        "me",
        "mean",
        "meanwhile",
        "merely",
        "might",
        "more",
        "moreover",
        "most",
        "mostly",
        "much",
        "must",
        "my",
        "myself",
        "n",
        "name",
        "namely",
        "nd",
        "near",
        "nearly",
        "necessary",
        "need",
        "needs",
        "neither",
        "never",
        "nevertheless",
        "new",
        "next",
        "nine",
        "no",
        "nobody",
        "non",
        "none",
        "noone",
        "nor",
        "normally",
        "not",
        "nothing",
        "novel",
        "now",
        "nowhere",
        "o",
        "obviously",
        "of",
        "off",
        "often",
        "oh",
        "ok",
        "okay",
        "old",
        "on",
        "once",
        "one",
        "ones",
        "only",
        "onto",
        "or",
        "other",
        "others",
        "otherwise",
        "ought",
        "our",
        "ours",
        "ourselves",
        "out",
        "outside",
        "over",
        "overall",
        "own",
        "p",
        "particular",
        "particularly",
        "per",
        "perhaps",
        "placed",
        "please",
        "plus",
        "possible",
        "presumably",
        "probably",
        "provides",
        "q",
        "que",
        "quite",
        "qv",
        "r",
        "rather",
        "rd",
        "re",
        "really",
        "reasonably",
        "regarding",
        "regardless",
        "regards",
        "relatively",
        "respectively",
        "right",
        "s",
        "said",
        "same",
        "saw",
        "say",
        "saying",
        "says",
        "second",
        "secondly",
        "see",
        "seeing",
        "seem",
        "seemed",
        "seeming",
        "seems",
        "seen",
        "self",
        "selves",
        "sensible",
        "sent",
        "serious",
        "seriously",
        "seven",
        "several",
        "shall",
        "she",
        "should",
        "since",
        "six",
        "so",
        "some",
        "somebody",
        "somehow",
        "someone",
        "something",
        "sometime",
        "sometimes",
        "somewhat",
        "somewhere",
        "soon",
        "sorry",
        "specified",
        "specify",
        "specifying",
        "still",
        "sub",
        "such",
        "sup",
        "sure",
        "t",
        "take",
        "taken",
        "tell",
        "tends",
        "th",
        "than",
        "thank",
        "thanks",
        "thanx",
        "that",
        "thats",
        "the",
        "their",
        "theirs",
        "them",
        "themselves",
        "then",
        "thence",
        "there",
        "thereafter",
        "thereby",
        "therefore",
        "therein",
        "theres",
        "thereupon",
        "these",
        "they",
        "think",
        "third",
        "this",
        "thorough",
        "thoroughly",
        "those",
        "though",
        "three",
        "through",
        "throughout",
        "thru",
        "thus",
        "to",
        "together",
        "too",
        "took",
        "toward",
        "towards",
        "tried",
        "tries",
        "truly",
        "try",
        "trying",
        "twice",
        "two",
        "u",
        "un",
        "under",
        "unfortunately",
        "unless",
        "unlikely",
        "until",
        "unto",
        "up",
        "upon",
        "us",
        "use",
        "used",
        "useful",
        "uses",
        "using",
        "usually",
        "uucp",
        "v",
        "value",
        "various",
        "very",
        "via",
        "viz",
        "vs",
        "w",
        "want",
        "wants",
        "was",
        "way",
        "we",
        "welcome",
        "well",
        "went",
        "were",
        "what",
        "whatever",
        "when",
        "whence",
        "whenever",
        "where",
        "whereafter",
        "whereas",
        "whereby",
        "wherein",
        "whereupon",
        "wherever",
        "whether",
        "which",
        "while",
        "whither",
        "who",
        "whoever",
        "whole",
        "whom",
        "whose",
        "why",
        "will",
        "willing",
        "wish",
        "with",
        "within",
        "without",
        "wonder",
        "would",
        "would",
        "x",
        "y",
        "yes",
        "yet",
        "you",
        "your",
        "yours",
        "yourself",
        "yourselves",
        "z",
        "zero",
    ]
    nltk_stopwords = stopwords.words('english')
    stop_words_list.extend(nltk_stopwords)
    stop_words_set = set(stop_words_list)

    # 语料目录,若路劲结尾不是.txt，那么该路径下的所有文件夹下的所有文件都是语料
    corpus_root_path_dict = {
        'convote_v1.1': [
            '../convote_v1.1/convote_v1.1/data_stage_one',
            '../convote_v1.1/convote_v1.1/data_stage_two',
            '../convote_v1.1/convote_v1.1/data_stage_three',
        ],
        'eng_news_2020_30K': [
            '../eng_news_2020_30K/eng_news_2020_30K/eng_news_2020_30K-sentences.txt'
        ],
        'eng_wikipedia_2016_10K': [
            '../eng_wikipedia_2016_10K/eng_wikipedia_2016_10K/eng_wikipedia_2016_10K-sentences.txt'
        ],
        'eng-uk_web-public_2018_10K': [
            '../eng-uk_web-public_2018_10K/eng-uk_web-public_2018_10K/eng-uk_web-public_2018_10K-sentences.txt'
        ],
        'review_polarity': [
            '../review_polarity/txt_sentoken/neg',
            '../review_polarity/txt_sentoken/pos'
        ],
        'rt-polaritydata': [
            '../rt-polaritydata/rt-polaritydata'
        ],
        'scale_whole_review': [
            '../scale_whole_review/scale_whole_review/Dennis+Schwartz/txt.parag',
            '../scale_whole_review/scale_whole_review/James+Berardinelli/txt.parag',
            '../scale_whole_review/scale_whole_review/Scott+Renshaw/txt.parag',
            '../scale_whole_review/scale_whole_review/Steve+Rhodes/txt.parag'
        ]
    }

    # 三种语料选择方式：'all', 'include', 'exclude'
    corpus_selection_mode = 'all'
    total_txt_file_path_list = []
    if corpus_selection_mode == 'all':
        for corpus_name in list(corpus_root_path_dict.keys()):
            sub_txt_file_path_list = corpus_root_path_dict[corpus_name]
            for file_path in sub_txt_file_path_list:
                if file_path[-4:] == '.txt':
                    total_txt_file_path_list.append(file_path)
                else:
                    tmp = get_all_txt_file(Path(file_path))
                    total_txt_file_path_list.extend(tmp)
    all_file_num = len(total_txt_file_path_list)

    # 拼接total_txt_file_path_list中所有的文件
    all_clean_txt_path = './clean_corpus/clean_corpus.txt'
    wnl = WordNetLemmatizer()  # 用于还原单词原型
    with open(all_clean_txt_path, 'a+') as f_clean:
        for count, file_path in enumerate(total_txt_file_path_list):
            try:
                with open(file_path, 'r') as f:
                    lines = f.readlines()
                    for line in lines:
                        line = line.strip('\n').lower()
                        pure_line = remove_num_and_punct(line)  # 删除所有数字和标点符号
                        tokens = word_tokenize(pure_line)  # 分词
                        tokens_no_stopwords = [word for word in tokens if not word in stop_words_set]  # 删除所有停用词
                        tagged_sent = pos_tag(tokens_no_stopwords)  # 获取所有单词的tag
                        lemmas_sent = []
                        for tag in tagged_sent:
                            wordnet_pos = get_wordnet_pos(tag[1]) or wordnet.NOUN
                            lemmas_sent.append(wnl.lemmatize(tag[0], pos=wordnet_pos))  # 词形还原
                        clean_line = ' '.join(lemmas_sent)
                        # 立马写入清理干净的句子
                        f_clean.write(clean_line+'\n')
            except:
                pass
            print(f'文件进度：当前文件id/所有文件数量/文件名称[{count}/{all_file_num} @ {file_path}].')
            f.close()
        f_clean.close()
